services:
  postgres:
    image: postgres:17
    container_name: finance-tracker-postgres-db
    environment:
      POSTGRES_DB: finance_tracker_db
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: 1234509876
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: